blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github. com/AmmarAhmedl200961/the-archive/discussions
    about: For general questions, suggestions, or community chat